version: '3.9'

services:
  mongodb-sistercompose:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: herliananur
      MONGO_INITDB_ROOT_PASSWORD: herliananur
      MONGO_INITDB_DATABASE: admin
