version: '3.9'

services:
  mongodb-network:
    image: mongo:latest
    container_name: mongodb-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: herliananur
      MONGO_INITDB_ROOT_PASSWORD: herliananur
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

networks:
  network_example: