version: '3.9'

services:
  app-healthcheck:
    container_name: app-healthcheck
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.0"
    environment:
      - "APP_PORT=8080"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
