version: '3.9'

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: herliananur
      MONGO_INITDB_ROOT_PASSWORD: herliananur
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: bind
        source: "./data-mongo2"
        target: "/data/db"
        read_only: false