version: '3.9'

services:
  mongodb-example-depends:
    image: mongo:latest
    container_name: mongodb-example-depends
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: herliananur
      MONGO_INITDB_ROOT_PASSWORD: herliananur
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    depends_on:
      - mongodb-example-depends
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: herliananur
      ME_CONFIG_MONGODB_ADMINPASSWORD: herliananur
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example

networks:
  network_example:
